### ISSUE TITLE
Training notebook

### ISSUE THREAD

**Issue by klock18** [liaopeiyuan/TransferDet#4]
Hi!

Awesome that you released your code, I am trying to extend your pipeline to include more images for the STAC component.

However, I have spent many hours trying to even get train_baseline.py working and was wondering if you had a training notebook you could release so I can speed up the process?

In case you had a solution I am now stuck with this error:

Traceback (most recent call last):00000, time: 0.45314
  File "train_baseline.py", line 470, in <module>
    run_training()
  File "train_baseline.py", line 453, in run_training
    fitter.fit(train_loader, val_loader)
  File "train_baseline.py", line 294, in fit
    summary_loss = self.train_one_epoch(train_loader)
  File "train_baseline.py", line 358, in train_one_epoch
    loss, _, _ = self.model(images, boxes, labels)
  File "/home/loc103/anaconda3/envs/stac/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

UPDATE: I have chnaged my code to this but I am running out of memory with CUDA after about 7 training steps and a batchsize of 1.

            target_res = {}
            
            boxes = [target['boxes'].to(self.device).float() for target in targets]
            labels = [target['labels'].to(self.device).float() for target in targets]
            
            target_res['bbox'] = boxes
            target_res['cls'] = labels 
            
            self.optimizer.zero_grad()
            # 
            # targets
            
            outputs = self.model(images, target_res)
            loss = outputs['loss']
            
            loss.backward()
            
    
            # with amp.scale_loss(loss, self.optimizer) as scaled_loss:
            #     scaled_loss.backward()        

            summary_loss.update(loss.detach().item(), batch_size)

Thanks!

**Comment by klock18** [comment]
Or if you could please release the necessary baselines for training the STAC model that would be awesome!

**Comment by klock18** [comment]
To fix the CUda issue I just used tf_efficientdet_d0 instead of tf_efficientdet_d6
